#' Add a header to the subgroup table
#'
#' This function adds a header to the table generated by `subgroup_table_binomial()`.
#'
#' @param data a data frame generated by `subgroup_table_binomial()`.
#' @param group1_lbl a character vector containing a label for treatment group 1.
#'  Each row of the vector will be translated into a separate line in the
#'  resulting data set.
#' @param group2_lbl a character vector containing a label for treatment group 2.
#' @return A tibble ready for input into `forestplot::forestplot()`.
#' @seealso [forestplotutil::subgroup_table_binomial] generates the table for which this header is intended.
#' @export
#' @examples
#' data(knee, package="catdata")
#'
#' knee %>% mutate(Th = factor(Th),
#'                 Sex = factor(Sex),
#'                 R4_improved = factor(if_else(R4 < R1, 1, 0))) ->
#'   knee
#' formula_overall = "R4_improved ~ Th + R1"
#' knee %>%
#'   subgroup_table_binomial(data = .,
#'                           formula_overall,
#'                           formulas = list(
#'                             Sex = "R4_improved ~ Th*Sex + R1"
#'                           ),
#'                           formulas_subgroups = list(
#'                             Sex = formula_overall
#'                           ),
#'                           group = "Th",
#'                           outcome = "R4_improved",
#'                           outcome_positive = 1)  %>%
#'   add_header(., group1_lbl = c("Improvement in", "placebo group"),
#'              group2_lbl = c("Improvement in", "treatment group")) ->
#'   res
add_header <- function(data, group1_lbl = c("", ""), group2_lbl = c("", "")){
  group_in_data = "group1" %in% names(data)
  if(group_in_data){
    if(is.null(group1_lbl)){
      group1_lbl = c("", "group1")
    }
    if(is.null(group2_lbl)){
      group2_lbl = c("", "group2")
    }
  } else{
    group1_lbl = c("", "")
    group2_lbl = group1_lbl
  }
  max_length = max(length(group1_lbl), length(group2_lbl))
  header <- tibble(subgroup = c(rep("", max_length-1), "Subgroup"),
                   group1 = c(rep("", max_length-length(group1_lbl)), group1_lbl),
                   group2 = c(rep("", max_length-length(group2_lbl)), group2_lbl),
                   OR = c(rep("", max_length-2), "Odds ratio", "[95% CI]"),
                   summary = TRUE,
                   p = c(rep("", max_length-1), "p"))
  if(!group_in_data){
    header <- header[, -which(names(header) %in% c("group1", "group2"))]
  }
  res <- bind_rows(header,
                   data)
  return(res)

}
